version: '3'

services:
  proxy:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=wnl.lk
      - VALIDATION=http
      - SUBDOMAINS=drive, #optional
      - CERTPROVIDER= #optional
      - PROPAGATION= #optional
      - EMAIL=dasun@wnl.lk #optional
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./proxy/conf/nextcloud.subdomain.conf:/config/nextcloud.subdomain.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    networks:
      - proxy-tier   
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env
  redis:
    image: redis:alpine
    restart: always
    networks:
      - proxy-tier
      - default
  nextcloud:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - OBJECTSTORE_S3_HOST=${OBJECTSTORE_S3_HOST}
      - OBJECTSTORE_S3_BUCKET=${OBJECTSTORE_S3_BUCKET}
      - OBJECTSTORE_S3_KEY=${OBJECTSTORE_S3_KEY}
      - OBJECTSTORE_S3_SECRET=${OBJECTSTORE_S3_SECRET}
      - OBJECTSTORE_S3_REGION=${OBJECTSTORE_S3_REGION}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
    env_file:
      - db.env
      - s3.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
  volumes:
    db:
    nextcloud:

networks:
  proxy-tier: 
  
